name: Scott Luptowski
description: The blog and portfolio of Scott Luptowski, a web developer and digital strategist in New York City.
url: http://www.scottluptowski.com
markdown: redcarpet
pygments: true
permalink: /posts/:title